name: Build for Linux

on:
  push:
    branches: [ "main", "workflow" ]
  pull_request:
    branches: [ "main", "workflow" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install package dependencies.
      run: |
        sudo apt-get install -y git \
          cmake \
          doxygen \
          libcairo2-dev \
          libncurses-dev
    
    - name: Checkout code including submodule dependencies.
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure libbase through CMake.
      # Configure CMake in a 'build' subdirectory.
      run: |
        cmake -B ${{github.workspace}}/build

    - name: Build libbase.
      # Build your program with the given configuration
      run: |
        cmake --build ${{github.workspace}}/build

    - name: Build documentation.
      run: cmake --build ${{github.workspace}}/build --target doc

    # - name: Run all tests
    #   working-directory: ${{github.workspace}}/build
    #   # Execute tests defined by the CMake configuration.
    #   # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
    #   run: |
    #     ctest --test-dir ${{github.workspace}}/build

